---
title: "qpcr processing"
author: "Dan Weinberger"
date: "12/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
#install.packages("readxl")
library(readxl)
#install.packages("xlsx")
#library(xlsx)
library(reshape2)
```

### Specify the names of the files you want to import

```{r}
file.names.import<- c('Q1.xls','Q2.xls', 'Q3.xls','Q4.xls', 'Q5.xls')

```

```{r}
## Import the files and combine into a single dataframe

import.fun<-function(ds.name, lognumber){
  ds.in<-read_excel(paste0("./data/",ds.name), skip=19)
  ds.in$log.number<- gsub( " .*$", "", ds.name )
  return(ds.in)
}
file.list<-lapply(file.names.import, import.fun)

ds<-do.call('rbind.data.frame',file.list)

```

```{r}
#Minor cleaning

ds$Sample[ds$Content=='NTC']<-'ntc'
ds$Cq<-as.numeric(as.character(ds$Cq))
ds$Cq[is.na(ds$Cq)]<- 45
ds$Cq[is.nan(ds$Cq)]<- 45

ds<-ds[order(ds$Target, ds$Sample),]
ds$Cq<-round(ds$Cq)
names(ds)[names(ds)=='Cq']<-'Ct'
```

```{r}
#count replicates
#Split the data by target and sample
ds.spl<-split(ds, paste0(ds$Sample,ds$Target))
ds.spl<-lapply(ds.spl, function(x){ 
  x$replicate= 1:nrow(x)
  return(x)
})
ds<-do.call('rbind.data.frame', ds.spl)
```


```{r}
## Reshape the data so that we have lytA and piaB results adjacent to each other

ds.samples<-ds[!(ds$Sample %in% c('-1','-2','-3','-4','-5','ntc','BL')) ,  ]
#ds.samples<-ds
ds2<-ds.samples[c('Target','Sample','Ct','log.number','replicate')]
ds.m<-melt(ds2, id.vars=c('Target','Sample','log.number','replicate'))
```

all results on same row, with replicates
```{r}
ds.samplewise<-dcast(ds.m, Sample~Target+replicate, fun.aggregate = mean)
#ds.samplewise
```

```{r}
#Which columns have lytA results? piaB results
lytA.cols<-grep('LYTA',  toupper(names(ds.samplewise)))
piaB.cols<-grep('PIAB',  toupper(names(ds.samplewise)))

pos.neg<-ds.samplewise[,-1, drop=F]
posneg.lytA.cols<-grep('LYTA', toupper(names(pos.neg)))
posneg.piaB.cols<-grep('PIAB', toupper(names(pos.neg)))
pos.neg[pos.neg<40] <-1
pos.neg[pos.neg>=40] <-0

ds.samplewise$lytA.pos<-apply(pos.neg[,posneg.lytA.cols,drop=F],1,max, na.rm=T)
ds.samplewise$piaB.pos<-apply(pos.neg[,posneg.piaB.cols,drop=F],1,max, na.rm=T)

ds.samplewise$both.pos<-0
ds.samplewise$both.pos<-ds.samplewise$lytA.pos * ds.samplewise$piaB.pos

```

```{r}
mat.print<-ds.samplewise[, c(1,lytA.cols, piaB.cols)]
mat.print<-mat.print[!is.na(mat.print$Sample),]
all.miss<-apply(mat.print[,-1],2, function(x1) length(x1)==sum(is.nan(x1) ))
if (sum(all.miss)>0){
cbind.data.frame('Sample'=mat.print[,1],mat.print[,-1][,-which(all.miss==1)])
}else{
  mat.print
}
```


## Pneumo positive samples (lytA and piaB+)
```{r}
mat.print<-ds.samplewise[ds.samplewise$both.pos==1 , c(1,lytA.cols, piaB.cols)]
mat.print<-mat.print[!is.na(mat.print$Sample),]
all.miss<-apply(mat.print[,-1],2, function(x1) length(x1)==sum(is.nan(x1) ))
if (sum(all.miss)>0){
cbind.data.frame('Sample'=mat.print[,1],mat.print[,-1][,-which(all.miss==1)])
}else{
  mat.print
}
```

## LytA pos, piaB neg to reculture
```{r}
mat.print<-ds.samplewise[ds.samplewise$lytA.pos==1 & ds.samplewise$piaB.pos==0 , c(1,lytA.cols, piaB.cols)]
mat.print<-mat.print[!is.na(mat.print$Sample),]
all.miss<-apply(mat.print[,-1],2, function(x1) length(x1)==sum(is.nan(x1) ))
if (sum(all.miss)>0){
cbind.data.frame('Sample'=mat.print[,1],mat.print[,-1][,-which(all.miss==1)])
}else{
  mat.print
}
```

## To retest by qPCR (piaB pos and lytA neg)

```{r}
mat.print<-ds.samplewise[ds.samplewise$lytA.pos==0 & ds.samplewise$piaB.pos==1 , c(1,lytA.cols, piaB.cols)]
mat.print<-mat.print[!is.na(mat.print$Sample),]
all.miss<-apply(mat.print[,-1],2, function(x1) length(x1)==sum(is.nan(x1) ))
if (sum(all.miss)>0){
cbind.data.frame('Sample'=mat.print[,1],mat.print[,-1][,-which(all.miss==1)])
}else{
  mat.print
}
```

#Export the dataset

```{r}
write.csv(out.ds, paste0('qPCR_results_aggregated_',Sys.Date(), '.csv') )
```




