---
title: "qpcr processing"
author: "Dan Weinberger"
date: "12/16/2019"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#install.packages("readxl")
library(readxl)
library(reshape2)
library(shiny)
```

```{r}
## function to Import the files 
import.fun<-function(ds.name, lognumber){
  ds.in<-read_excel(paste0("./data/",ds.name), skip=19)
  ds.in$log.number<- gsub( " .*$", "", ds.name )
  return(ds.in)
}
```
## Specify the names of the files you want to import

```{r}
#shinyApp(

#  ui = fluidPage(
 fileInput("excel_input", "Choose .xlsx File",
        accept = c(
          "xlsx",
          ".xls"),
        multiple=TRUE
        )#,
 #fluidRow(tableOutput('CtTable')),
  #fluidRow(tableOutput('PneumoPosTable')),

 #),

```

```{r}
#server=function(input,output){
  ds1<-reactive({
        req(input$excel_input$name)

      file.names.import<-input$excel_input$name
      file.list<-lapply(file.names.import, import.fun)
      ds<-do.call('rbind.data.frame',file.list)  
      #Minor cleaning
        ds$Sample[ds$Content=='NTC']<-'ntc'
        ds$Cq<-as.numeric(as.character(ds$Cq))
        ds$Cq[is.na(ds$Cq)]<- 45
        ds$Cq[is.nan(ds$Cq)]<- 45
        ds<-ds[order(ds$Target, ds$Sample),]
        ds$Cq<-round(ds$Cq)
        names(ds)[names(ds)=='Cq']<-'Ct'

        
        #count replicates; Split the data by target and sample
        ds.spl<-split(ds, paste0(ds$Sample,ds$Target))
        ds.spl<-lapply(ds.spl, function(x){ 
          x$replicate= 1:nrow(x)
          return(x)
        })
        ds<-do.call('rbind.data.frame', ds.spl)
        
        ## Reshape the data so that we have lytA and piaB results adjacent to each other
        ds.samples<-ds[!(ds$Sample %in% c('-1','-2','-3','-4','-5','ntc','BL')) ,  ]
        #ds.samples<-ds
        ds2<-ds.samples[c('Target','Sample','Ct','log.number','replicate')]
        ds.m<-melt(ds2, id.vars=c('Target','Sample','log.number','replicate'))
        #all results on same row, with replicates
    ds.samplewise<-dcast(ds.m, Sample~Target+replicate, fun.aggregate = mean)
    pos.neg<-ds.samplewise[,-1, drop=F]
     lytA.cols<-grep('LYTA',  toupper(names(ds.samplewise)))
  piaB.cols<-grep('PIAB',  toupper(names(ds.samplewise)))
  posneg.lytA.cols<-grep('LYTA', toupper(names(pos.neg)))
  posneg.piaB.cols<-grep('PIAB', toupper(names(pos.neg)))
  pos.neg[pos.neg<40] <-1
  pos.neg[pos.neg>=40] <-0
  ds.samplewise$lytA.pos<-apply(pos.neg[,posneg.lytA.cols,drop=F],1,max)
  ds.samplewise$piaB.pos<-apply(pos.neg[,posneg.piaB.cols,drop=F],1,max)
  ds.samplewise$both.pos<-0
  ds.samplewise$both.pos<-ds.samplewise$lytA.pos * ds.samplewise$piaB.pos
  formatted<-list('ds'=ds.samplewise,'piaB.cols'=piaB.cols,'lytA.cols'=lytA.cols )
return(formatted)

  })
```

## Pneumo positive samples (lytA+ AND piaB+)
```{r}
 renderTable({
     ds.samplewise<-ds1()$ds
ds.samplewise[ds.samplewise$both.pos==1, c(1, ds1()$lytA.cols, ds1()$piaB.cols)]
}, bordered=T)
```

## To reculture and check species (lytA+ and piaB-)
```{r}
 renderTable({
     ds.samplewise<-ds1()$ds
ds.samplewise[ds.samplewise$piaB.pos==0 &ds.samplewise$lytA.pos==1, c(1, ds1()$lytA.cols, ds1()$piaB.cols) ]
}, bordered=T)
```

## To repeat qPCR (lytA- and piaB+)
```{r}
 renderTable({
     ds.samplewise<-ds1()$ds
ds.samplewise[ds.samplewise$piaB.pos==1 &ds.samplewise$lytA.pos==0, c(1, ds1()$lytA.cols, ds1()$piaB.cols) ]
}, bordered=T)
```

## Print all samples
```{r}
    renderTable({
      ds1()$ds[,c(1,ds1()$lytA.cols, ds1()$piaB.cols)]
    }, bordered=T)
```

